---
title: "pro_part2"
author: "Shuangyu Zhao"
date: "2023-04-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(caret)
library(ggplot2)
library(class)
library(e1071)
library(MASS)
library(pROC)
```


according to the pronounciation, determine whether this words has r or t
```{r}
rtdata <- read.csv("/Users/apple/Desktop/STT811_appl_stat_model/pro/distinguishr_t.csv")
dim(rtdata)
```
target rdata[, 52]
feature rdata[, c(2:50)]
 r-1, t-0



```{r}
set.seed(888)
set.seed(888)
split_pct <- 0.7
n <- length(rtdata$token)*split_pct # train size
row_samp <- sample(1:length(rtdata$token), n, replace = FALSE) 
train <- rtdata[row_samp,]
test <- rtdata[-row_samp,]

```
```{r}
train_feature <- train[, c(2:50)]
train_target <- train[, 52]
test_feature <- test[, c(2:50)]
test_target <- test[, 52]

```
```{r}
table(train_target)
```


logistic regression
```{r}
rtdata_lr_mod <- glm(data = train_feature, train_target ~ ., family = binomial)
test_pred_lr <- predict(rtdata_lr_mod,test_feature, type = "response")
train_cm_lr <- confusionMatrix(as.factor(as.integer(2*rtdata_lr_mod$fitted.values)), reference = as.factor(train_target))
test_cm_lr <- confusionMatrix(as.factor(as.integer(2*test_pred_lr)), reference = as.factor(test_target))
```

```{r}
# extract the confusion matrix as a dataframe
confusion_trainlr <- data.frame(train_cm_lr$table)

# create a ggplot of the confusion matrix
ggplot(data = confusion_trainlr, aes(x = Prediction, y = Reference, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = Freq), color = "white") +
  labs(title = "Confusion Matrix",
       x = "Predicted",
       y = "Actual",
       fill = "Frequency")
```
```{r}
# extract the confusion matrix as a dataframe
confusion_testlr <- data.frame(test_cm_lr$table)

# create a ggplot of the confusion matrix
ggplot(data = confusion_testlr, aes(x = Prediction, y = Reference, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = Freq), color = "white") +
  labs(title = "Confusion Matrix",
       x = "Predicted",
       y = "Actual",
       fill = "Frequency")
```
```{r}
# calculate accuracy
 test_cm_lr$overall["Accuracy"]

# calculate F1 score
test_cm_lr$byClass["F1"]
# precision
 test_cm_lr$byClass["Pos Pred Value"]
# recall
 test_cm_lr$byClass["Sensitivity"]
```
```{r}
# Load the pROC package
library(pROC)

# Compute the ROC curve
roc_curve <- roc(test_target, test_pred_lr)

# Plot the ROC curve
plot(roc_curve, main = "ROC Curve", xlab = "False Positive Rate", ylab = "True Positive Rate", print.auc = TRUE, legacy.axes = TRUE)
```
LDA
```{r}
rdata_mod_lda <- lda(data = train_feature, train_target ~ .)
test_pred_lda <- predict(rdata_mod_lda,test_feature, type = "response")$class
test_cm_lda <- confusionMatrix(as.factor(test_pred_lda), reference = as.factor(test_target))
train_cm_lda <- confusionMatrix(data = as.factor(predict(rdata_mod_lda, train_feature, type = "response")$class), reference = as.factor(train_target))
```

```{r}
# Compute the ROC curve
roc_curve <- roc(test_target,  predict(rdata_mod_lda, newdata = test_feature)$posterior[, 2])

# Plot the ROC curve
plot(roc_curve, main = "ROC Curve", xlab = "False Positive Rate", ylab = "True Positive Rate", print.auc = TRUE, legacy.axes = TRUE)
```
QDA
```{r}
rdata_mod_qda <- qda(data = train_feature, train_target ~ .)
test_pred_qda <- predict(rdata_mod_qda,test_feature, type = "response")$class
test_cm_qda <- confusionMatrix(as.factor(test_pred_qda), reference = as.factor(test_target))
train_cm_qda <- confusionMatrix(data = as.factor(predict(rdata_mod_qda, train_feature, type = "response")$class), reference = as.factor(train_target))
```

```{r}
# Compute the ROC curve
roc_curve <- roc(test_target,  predict(rdata_mod_qda, newdata = test_feature)$posterior[, 2])

# Plot the ROC curve
plot(roc_curve, main = "ROC Curve", xlab = "False Positive Rate", ylab = "True Positive Rate", print.auc = TRUE, legacy.axes = TRUE)
```

KNN
```{r}
knn_mod <- knn(train_feature, test_feature, cl = train_target , k = 3, prob = TRUE)
knn_cm <- confusionMatrix(knn_mod , reference = as.factor(test_target))

# extract the confusion matrix as a dataframe
confusion_knn <- data.frame(knn_cm$table)

# calculate F1 score
knn_cm$byClass["F1"]
```

```{r}
knn_mod <- knn(train_feature, test_feature, cl = train_target , k = 5, prob = TRUE)
knn_cm <- confusionMatrix(knn_mod , reference = as.factor(test_target))

# extract the confusion matrix as a dataframe
confusion_knn <- data.frame(knn_cm$table)

# create a ggplot of the confusion matrix
ggplot(data = confusion_knn, aes(x = Prediction, y = Reference, fill = Freq)) +
  geom_tile() +
  geom_text(aes(label = Freq), color = "white") +
  labs(title = "Confusion Matrix",
       x = "Predicted",
       y = "Actual",
       fill = "Frequency")
```

```{r}
# calculate accuracy
 knn_cm$overall["Accuracy"]

# calculate F1 score
knn_cm$byClass["F1"]
# precision
 knn_cm$byClass["Pos Pred Value"]
# recall
 knn_cm$byClass["Sensitivity"]
```

```{r}
knn_mod <- knn(train_feature, test_feature, cl = train_target , k = 7, prob = TRUE)
knn_cm <- confusionMatrix(knn_mod , reference = as.factor(test_target))

# extract the confusion matrix as a dataframe
confusion_knn <- data.frame(knn_cm$table)

# calculate F1 score
knn_cm$byClass["F1"]
```

```{r}

# Compute the ROC curve
roc_curve <- roc(test_target,  attr(knn_mod, "prob"))

# Plot the ROC curve
plot(roc_curve, main = "ROC Curve", xlab = "False Positive Rate", ylab = "True Positive Rate", print.auc = TRUE, legacy.axes = TRUE)
```

```{r}
knn_mod <- knn(train_feature, test_feature, cl = train_target , k = 9, prob = TRUE)
knn_cm <- confusionMatrix(knn_mod , reference = as.factor(test_target))

# extract the confusion matrix as a dataframe
confusion_knn <- data.frame(knn_cm$table)

# calculate F1 score
knn_cm$byClass["F1"]
```

SVM with multiple kernels

linear, polynomial, radial, sigmoid


```{r}
# linear
# perform grid search using cross-validation
svm_linear_c01 <- tune.svm(x = train_feature, y = train_target, cost = 0.1, gamma=0.1, kernel = "linear", scale = FALSE)

test_pred_svm_linearc01 <- predict(svm_linear_c01,test_feature, type = "response")
cm_test_pred_svm_linearc01 <- confusionMatrix(data = as.factor(test_pred_svm_linearc01), reference = as,factor(test_target))
cm_test_pred_svm_linearc01$table
```










QDA

















































